

#pragma once


enum class StateKey {
	MOUSE_X,
	MOUSE_Y,
	PLUGIN_NAME,
	PLUGIN_DESCRIPTION,
	PLUGIN_TYPE,
	PLUGIN_VERSION,
	PLUGIN_ERRORS,
	PLUGIN_STAMP,
	ANIMATOR_CHANNEL_FRAME,
	ANIMATOR_CHANNEL_FRAME_END,
	ANIMATOR_CHANNEL_FRAME_START,
	ANIMATOR_CHANNEL_FRAME_STEP,
	ANIMATOR_CHANNEL_FRAME_RATE,
	ANIMATOR_CHANNEL_END_BEHAVIOR,
	END_KEY
};
